### ISSUE TITLE
Issue list with RTL(right-to-left) pattern

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1296]
```
Test Environment 

1. Wordpress 5.1
2. rtMedia Core 4.5.6
3. BuddyPress - 4.2.0
4. RTL Tester Plugin 1.1 (https://wordpress.org/plugins/rtl-tester/)
```
---------

## 1. Backend 

Please correct some minor changes which appears incase of RTL.

- [x] 1.1 `rt Logo` need some space. 

![logo](https://user-images.githubusercontent.com/15173772/53867806-9a167080-401a-11e9-85dd-1c38eb164d68.png)

------

- [x] 1.2 Font family gets changed for the mentioned class below. Please check this under `rtMedia Settings Screen`.

```
1. .rtm-tabs
2. .rtm-option-title
3. .hndle
4. .nav-tab-wrapper
5. .notice.notice-info.install-transcoder-notice.is-dismissible 
6. .updated.rtmedia-inspire-book-notice
7. .updated.rtmedia-pro-split-notice
```

Please check this link - https://nimb.ws/Cghtyb

### Expected Font Family type

```
system-ui - 700×
Family
-apple-system, system-ui, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
```

### Actual Font Family type 
 
```
Tahoma - 700×
Family
Tahoma, Arial, sans-serif;
```
-------------

## 2. Frontend

- [x] 2.1  Album Page - `Pipe` symbol is misaligned. It should be between `Upload and Option button`
https://goo.gl/471KU4

- [x] 2.2 Listed below items should be right aligned.

```
1. Create an Album label
2. Album Title Label
3. Album Description Label
4. Create Album Button
5. The message is shown after the album is created
```
Please check this screen - https://goo.gl/BMc1o1

- [x] 2.3 Clicking upon `Option` button - shows `Add Album` button which goes out of boundary for some themes. 

1. Theme 2012 - https://goo.gl/ZqKZFu
2. Theme 2016 - https://goo.gl/eL4TtL

- [x] 2.4 Opening media in lightbox - Please check below details which are not aligned RTL pattern.

**Comment by pavanpatil1** [comment]
Cross-checked the issue. The fix is working fine. 

> 1.1 rt Logo needs some space.

The logo is shifted. 

![image](https://user-images.githubusercontent.com/44057535/144411985-854c6f9b-beb0-4f37-a76d-58a000f6a5a2.png)

---

> 2.1 Album Page - Pipe symbol is misaligned. It should be between Upload and Option button. 

Fixed
![image](https://user-images.githubusercontent.com/44057535/144412691-267f1b22-100c-49b2-a428-11ede70d0f0f.png)

---

> 2.2 Listed below items should be right aligned.

Fixed
![image](https://user-images.githubusercontent.com/44057535/144413593-f1328d1e-5086-47e1-8ee9-72ade2b0d1c8.png)

---

> 2.3 Clicking upon Option button - shows Add Album button which goes out of boundary for some themes.
Theme 2012 - https://goo.gl/ZqKZFu
Theme 2016 - https://goo.gl/eL4TtL

The themes are too old. Working with the latest themes.

---
 
> 2.4 Opening media in lightbox - Please check below details which are not aligned RTL pattern.

Fixed
![screenshot-newtab-2021 12 02-16_59_37](https://user-images.githubusercontent.com/44057535/144414178-49b3644c-3582-42e8-a9fb-0933546f44fb.png)
