### ISSUE TITLE
User should be navigated to the tab where the error has occured

### ISSUE THREAD

**Issue by kjnanda** [rtCamp/rtMedia#1475]
May we should display validation error summary.

**Scenario:** what if user enable upload term but forget to add a link or type link text and change the tab and then save the settings but settings are not saved. because it is an error on upload term tab and displayed inside that tab. So the user might confuse why settings are not saved. we must implement Validation Error Summary for that.

https://drive.google.com/file/d/1dMXRASJntwvmHdzy7KJPA0bz6F3KRoy1/view

**Comment by dishitpala** [comment]
@chandrapatel 
In other validations `alert` is used
So do we need to add `alert` for the above issue or go with `User should be navigated to the tab where the error has occurred`

`User should be navigated to the tab where the error has occurred` this will take time to refactor the code.

@kjnanda suggested we can also add navigation to alert box as well
Eg: `Other Settings` -> `Link for "Terms of Service" page`

So that user can know where S/he needs to fix the validation 

CC @kjnanda

**Comment by chandrapatel** [comment]
@dishitpala First check what other possibilities are there to display validation error messages to users and how we can improve it like displaying all of the validation errors at once or highlight tabs so that user can see what tab settings having an error.

**Comment by dishitpala** [comment]
@kjnanda 

Here is my thought that how we can manage validation notification from a user perspective 
- We can highlight the tab where the user has put the wrong input ( As @chandrapatel suggested )
- We can also add the count for the validation error Eg: Display (2) Here `2` will be the error count so that user can have a number to fix the validation error
- We can use global object for validation so that we can use it for the addons as well.

**Comment by kjnanda** [comment]
@dishitpala I think we can go ahead with the points you listed down. 

> We can also add the count for the validation error Eg: Display (2) Here 2 will be the error count so that user can have a number to fix the validation error

Regarding this, I would need to see during the testing this should not break any UI and UX. 

But let's implement this. We can add improvements further.

CC @chandrapatel
