### ISSUE TITLE
 Option to add video and photo tab on the main menu

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1653]
Option to customize the media tab and place the video and photo tab on the main menu BuddyPress menu.
Currently, the menu looks like now....
`Activity - Profile - Friends - Groups -Media`

Instead of it can we show the menu like
`Activity - Profile - Friends - Groups - Video - Photo`

**Comment by thebengalboy** [comment]
Hi @pooja-muchandikar 

I have gone through it and it seems the way we have the media now is better manageable rather than the suggested way.

We have the following sub-menus under the `Media`:  All, Albums, Photos, Videos, Music, Documents, Playlists, Others, and Likes.

Now, let's say if we bring the Photos and Videos to the parent menu, that not all the users may want. Someone may want to have Playlists only on the parent menu, some other person may want to have Music.

Consider it like, Media is the parent and all the sub-menus are a child of it. So, child and parent should not have in the same menu line.

If you feel the same, then we can close this issue.

**Comment by pooja-muchandikar** [comment]
@thebengalboy 

Agree, but I think at least we can one filter for this requirement in our docs. What do you think about this?

**Comment by thebengalboy** [comment]
Yes, agree with that. We can have a developer doc mentioning the filter to bring any child menus to the parent.

Ok, @pooja-muchandikar; taking a note about filters and closing this issue for now 🤝
