### ISSUE TITLE
mediaelement-and-player.min.js - Time issue on Activity Stream

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1684]
On buddypress activity page when site loads, the standard WordPress/BuddyPress time format appears. That is, `5 days, 7 hours ago.`

A few seconds later, the time format changes to 5 days ago.

It should show the WP/BP time format.

Refer: https://drive.google.com/file/d/1-FJrDcdujECPP915Zse_t8D9DCNJfmd8/view

**Comment by abhijitrakas** [comment]
@pooja-muchandikar 

This happening because of [livestamp.js](https://github.com/mattbradley/livestampjs). On page load, `livestamp.js` library updating `timeago` text of comment/post.

Livestamp.js is using [Moment.js](https://momentjs.com/) library for `timeago` text format. This is loading from `BuddyPress` core. 

I am still checking this to fix it in rtMedia core. I will continue on this on Monday.
