### ISSUE TITLE
PHP freemius error after wordpress 4.4.2 update with rtMedia active

### ISSUE THREAD

**Issue by WithBenefitZ** [rtCamp/rtMedia#685]
My site recently auto updated to WordPress 4.4.2 and rtmedia began generating php errors.

The error message below:
Fatal error: Call to undefined function fs_get_ip() in …../buddypress-media/lib/freemius/config.php on line 86.
I rolled back to wordpress 4.4.1 but the error still showed on activating rtmedia.
I also disabled all plugins but the error still occurred.

Any idea on how to resolve the issue?

Thanks

**Comment by vovafeldman** [comment]
@WithBenefitZ I'm the lead developer of Freemius, the code that throws the error. I think it's happening due to a collision of old versions of our SDK. First of all, to resolve it rename `buddypress-media` folder to `buddypress-media.off` to temporary deactivate the plugin. 

Secondary, for me to investigate that further, could you please share your active plugins list? If you don't feel comfortable sharing it publicly, please contact me via [vova AT freemius DOT com].

**Comment by WithBenefitZ** [comment]
Thanks @vovafeldman . I'll send it to your email shortly.

**Comment by WithBenefitZ** [comment]
I just noticed the Activity Log plugin v2.2.8 also use freemius and the config.php does not have the fs_get_ip() function.
Their recent update v2.2.9 has the function in the config.php.
I will try updating and testing again.

**Comment by WithBenefitZ** [comment]
Hi @vovafeldman the Activity Log plugin was the issue. I updated the plugin and rtmedia is stable now.

Thanks for the tip when you said it might be due to a collision of old versions of the SDK.

**Comment by vovafeldman** [comment]
:+1: Thanks for the update.
