### ISSUE TITLE
Issue with next/prev in media popup with Load More and Pagination

### ISSUE THREAD

**Issue by BhargavBhandari90** [rtCamp/rtMedia#986]
Follow the steps to replicate the issue:

1. Go to rtMedia->settings->Display
2. Set `Number of media per page` => 3
3. Set `Media display pagination option` => `Load More`
4. Save it.
5. Goto front end, open any album (media page)
6. Click on the first media file and keep pressing the next navigation arrow.
7. Now, observe that it shows the first image after reached the limit. In our case after the 3rd image, it shows the 1st image whereas it should show the 4th image instead of the first image.

**Comment by NicestRudeGuy** [comment]
Understood this issue 

- I think since the image was not shown on the page currently or paginated with load more the lightbox wasn’t having the reference of the last image.  Ive seen these kind of lightbox implementation  where the images shown on the page are present in the lightbox gallery  not the hidden one.

- After clicking on the load more button and then tried this issue wasn't there so this confirms the first point.

- Also since the image isnt visible currently isnt that supposed to be hidden inside the lightbox gallery ?

**Comment by pooja-muchandikar** [comment]
>Also since the image isnt visible currently isnt that supposed to be hidden inside the lightbox gallery ?

I think no, as its gallery and we can show all the images from gallery in the lightbox. 

If it would be a post card where you are uploading media and viewing images from that card itself, then it will be valid scenario. But for gallery it is okay to show all images in lightbox.

**Comment by Pradeep1308** [comment]
@pooja-muchandikar This issue resolved as all images are visible in lightbox

```
PHP Version : 7.4.1
WordPress Version: 5.8.1
rtMedia Version: 4.6.7
```

**Comment by pooja-muchandikar** [comment]
Noted, 

If this is not valid anymore, I am closing this issue.
